
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MenuCategoryTranslation` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model MenuCategoryTranslation
 * 
 */
export type MenuCategoryTranslationModel = runtime.Types.Result.DefaultSelection<Prisma.$MenuCategoryTranslationPayload>

export type AggregateMenuCategoryTranslation = {
  _count: MenuCategoryTranslationCountAggregateOutputType | null
  _min: MenuCategoryTranslationMinAggregateOutputType | null
  _max: MenuCategoryTranslationMaxAggregateOutputType | null
}

export type MenuCategoryTranslationMinAggregateOutputType = {
  id: string | null
  language: $Enums.Language | null
  title: string | null
  description: string | null
  categoryId: string | null
}

export type MenuCategoryTranslationMaxAggregateOutputType = {
  id: string | null
  language: $Enums.Language | null
  title: string | null
  description: string | null
  categoryId: string | null
}

export type MenuCategoryTranslationCountAggregateOutputType = {
  id: number
  language: number
  title: number
  description: number
  categoryId: number
  _all: number
}


export type MenuCategoryTranslationMinAggregateInputType = {
  id?: true
  language?: true
  title?: true
  description?: true
  categoryId?: true
}

export type MenuCategoryTranslationMaxAggregateInputType = {
  id?: true
  language?: true
  title?: true
  description?: true
  categoryId?: true
}

export type MenuCategoryTranslationCountAggregateInputType = {
  id?: true
  language?: true
  title?: true
  description?: true
  categoryId?: true
  _all?: true
}

export type MenuCategoryTranslationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MenuCategoryTranslation to aggregate.
   */
  where?: Prisma.MenuCategoryTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MenuCategoryTranslations to fetch.
   */
  orderBy?: Prisma.MenuCategoryTranslationOrderByWithRelationInput | Prisma.MenuCategoryTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MenuCategoryTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MenuCategoryTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MenuCategoryTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MenuCategoryTranslations
  **/
  _count?: true | MenuCategoryTranslationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MenuCategoryTranslationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MenuCategoryTranslationMaxAggregateInputType
}

export type GetMenuCategoryTranslationAggregateType<T extends MenuCategoryTranslationAggregateArgs> = {
      [P in keyof T & keyof AggregateMenuCategoryTranslation]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMenuCategoryTranslation[P]>
    : Prisma.GetScalarType<T[P], AggregateMenuCategoryTranslation[P]>
}




export type MenuCategoryTranslationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MenuCategoryTranslationWhereInput
  orderBy?: Prisma.MenuCategoryTranslationOrderByWithAggregationInput | Prisma.MenuCategoryTranslationOrderByWithAggregationInput[]
  by: Prisma.MenuCategoryTranslationScalarFieldEnum[] | Prisma.MenuCategoryTranslationScalarFieldEnum
  having?: Prisma.MenuCategoryTranslationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MenuCategoryTranslationCountAggregateInputType | true
  _min?: MenuCategoryTranslationMinAggregateInputType
  _max?: MenuCategoryTranslationMaxAggregateInputType
}

export type MenuCategoryTranslationGroupByOutputType = {
  id: string
  language: $Enums.Language
  title: string
  description: string | null
  categoryId: string
  _count: MenuCategoryTranslationCountAggregateOutputType | null
  _min: MenuCategoryTranslationMinAggregateOutputType | null
  _max: MenuCategoryTranslationMaxAggregateOutputType | null
}

type GetMenuCategoryTranslationGroupByPayload<T extends MenuCategoryTranslationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MenuCategoryTranslationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MenuCategoryTranslationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MenuCategoryTranslationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MenuCategoryTranslationGroupByOutputType[P]>
      }
    >
  >



export type MenuCategoryTranslationWhereInput = {
  AND?: Prisma.MenuCategoryTranslationWhereInput | Prisma.MenuCategoryTranslationWhereInput[]
  OR?: Prisma.MenuCategoryTranslationWhereInput[]
  NOT?: Prisma.MenuCategoryTranslationWhereInput | Prisma.MenuCategoryTranslationWhereInput[]
  id?: Prisma.StringFilter<"MenuCategoryTranslation"> | string
  language?: Prisma.EnumLanguageFilter<"MenuCategoryTranslation"> | $Enums.Language
  title?: Prisma.StringFilter<"MenuCategoryTranslation"> | string
  description?: Prisma.StringNullableFilter<"MenuCategoryTranslation"> | string | null
  categoryId?: Prisma.StringFilter<"MenuCategoryTranslation"> | string
  category?: Prisma.XOR<Prisma.MenuCategoryScalarRelationFilter, Prisma.MenuCategoryWhereInput>
}

export type MenuCategoryTranslationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  language?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  category?: Prisma.MenuCategoryOrderByWithRelationInput
}

export type MenuCategoryTranslationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  language_categoryId?: Prisma.MenuCategoryTranslationLanguageCategoryIdCompoundUniqueInput
  AND?: Prisma.MenuCategoryTranslationWhereInput | Prisma.MenuCategoryTranslationWhereInput[]
  OR?: Prisma.MenuCategoryTranslationWhereInput[]
  NOT?: Prisma.MenuCategoryTranslationWhereInput | Prisma.MenuCategoryTranslationWhereInput[]
  language?: Prisma.EnumLanguageFilter<"MenuCategoryTranslation"> | $Enums.Language
  title?: Prisma.StringFilter<"MenuCategoryTranslation"> | string
  description?: Prisma.StringNullableFilter<"MenuCategoryTranslation"> | string | null
  categoryId?: Prisma.StringFilter<"MenuCategoryTranslation"> | string
  category?: Prisma.XOR<Prisma.MenuCategoryScalarRelationFilter, Prisma.MenuCategoryWhereInput>
}, "id" | "language_categoryId">

export type MenuCategoryTranslationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  language?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  categoryId?: Prisma.SortOrder
  _count?: Prisma.MenuCategoryTranslationCountOrderByAggregateInput
  _max?: Prisma.MenuCategoryTranslationMaxOrderByAggregateInput
  _min?: Prisma.MenuCategoryTranslationMinOrderByAggregateInput
}

export type MenuCategoryTranslationScalarWhereWithAggregatesInput = {
  AND?: Prisma.MenuCategoryTranslationScalarWhereWithAggregatesInput | Prisma.MenuCategoryTranslationScalarWhereWithAggregatesInput[]
  OR?: Prisma.MenuCategoryTranslationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MenuCategoryTranslationScalarWhereWithAggregatesInput | Prisma.MenuCategoryTranslationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"MenuCategoryTranslation"> | string
  language?: Prisma.EnumLanguageWithAggregatesFilter<"MenuCategoryTranslation"> | $Enums.Language
  title?: Prisma.StringWithAggregatesFilter<"MenuCategoryTranslation"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"MenuCategoryTranslation"> | string | null
  categoryId?: Prisma.StringWithAggregatesFilter<"MenuCategoryTranslation"> | string
}

export type MenuCategoryTranslationCreateInput = {
  id?: string
  language: $Enums.Language
  title: string
  description?: string | null
  category: Prisma.MenuCategoryCreateNestedOneWithoutMenuCategoryTranslationsInput
}

export type MenuCategoryTranslationUncheckedCreateInput = {
  id?: string
  language: $Enums.Language
  title: string
  description?: string | null
  categoryId: string
}

export type MenuCategoryTranslationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.EnumLanguageFieldUpdateOperationsInput | $Enums.Language
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.MenuCategoryUpdateOneRequiredWithoutMenuCategoryTranslationsNestedInput
}

export type MenuCategoryTranslationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.EnumLanguageFieldUpdateOperationsInput | $Enums.Language
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type MenuCategoryTranslationCreateManyInput = {
  id?: string
  language: $Enums.Language
  title: string
  description?: string | null
  categoryId: string
}

export type MenuCategoryTranslationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.EnumLanguageFieldUpdateOperationsInput | $Enums.Language
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MenuCategoryTranslationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.EnumLanguageFieldUpdateOperationsInput | $Enums.Language
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  categoryId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type MenuCategoryTranslationListRelationFilter = {
  every?: Prisma.MenuCategoryTranslationWhereInput
  some?: Prisma.MenuCategoryTranslationWhereInput
  none?: Prisma.MenuCategoryTranslationWhereInput
}

export type MenuCategoryTranslationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MenuCategoryTranslationLanguageCategoryIdCompoundUniqueInput = {
  language: $Enums.Language
  categoryId: string
}

export type MenuCategoryTranslationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  language?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
}

export type MenuCategoryTranslationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  language?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
}

export type MenuCategoryTranslationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  language?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  categoryId?: Prisma.SortOrder
}

export type MenuCategoryTranslationCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.MenuCategoryTranslationCreateWithoutCategoryInput, Prisma.MenuCategoryTranslationUncheckedCreateWithoutCategoryInput> | Prisma.MenuCategoryTranslationCreateWithoutCategoryInput[] | Prisma.MenuCategoryTranslationUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.MenuCategoryTranslationCreateOrConnectWithoutCategoryInput | Prisma.MenuCategoryTranslationCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.MenuCategoryTranslationCreateManyCategoryInputEnvelope
  connect?: Prisma.MenuCategoryTranslationWhereUniqueInput | Prisma.MenuCategoryTranslationWhereUniqueInput[]
}

export type MenuCategoryTranslationUncheckedCreateNestedManyWithoutCategoryInput = {
  create?: Prisma.XOR<Prisma.MenuCategoryTranslationCreateWithoutCategoryInput, Prisma.MenuCategoryTranslationUncheckedCreateWithoutCategoryInput> | Prisma.MenuCategoryTranslationCreateWithoutCategoryInput[] | Prisma.MenuCategoryTranslationUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.MenuCategoryTranslationCreateOrConnectWithoutCategoryInput | Prisma.MenuCategoryTranslationCreateOrConnectWithoutCategoryInput[]
  createMany?: Prisma.MenuCategoryTranslationCreateManyCategoryInputEnvelope
  connect?: Prisma.MenuCategoryTranslationWhereUniqueInput | Prisma.MenuCategoryTranslationWhereUniqueInput[]
}

export type MenuCategoryTranslationUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.MenuCategoryTranslationCreateWithoutCategoryInput, Prisma.MenuCategoryTranslationUncheckedCreateWithoutCategoryInput> | Prisma.MenuCategoryTranslationCreateWithoutCategoryInput[] | Prisma.MenuCategoryTranslationUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.MenuCategoryTranslationCreateOrConnectWithoutCategoryInput | Prisma.MenuCategoryTranslationCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.MenuCategoryTranslationUpsertWithWhereUniqueWithoutCategoryInput | Prisma.MenuCategoryTranslationUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.MenuCategoryTranslationCreateManyCategoryInputEnvelope
  set?: Prisma.MenuCategoryTranslationWhereUniqueInput | Prisma.MenuCategoryTranslationWhereUniqueInput[]
  disconnect?: Prisma.MenuCategoryTranslationWhereUniqueInput | Prisma.MenuCategoryTranslationWhereUniqueInput[]
  delete?: Prisma.MenuCategoryTranslationWhereUniqueInput | Prisma.MenuCategoryTranslationWhereUniqueInput[]
  connect?: Prisma.MenuCategoryTranslationWhereUniqueInput | Prisma.MenuCategoryTranslationWhereUniqueInput[]
  update?: Prisma.MenuCategoryTranslationUpdateWithWhereUniqueWithoutCategoryInput | Prisma.MenuCategoryTranslationUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.MenuCategoryTranslationUpdateManyWithWhereWithoutCategoryInput | Prisma.MenuCategoryTranslationUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.MenuCategoryTranslationScalarWhereInput | Prisma.MenuCategoryTranslationScalarWhereInput[]
}

export type MenuCategoryTranslationUncheckedUpdateManyWithoutCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.MenuCategoryTranslationCreateWithoutCategoryInput, Prisma.MenuCategoryTranslationUncheckedCreateWithoutCategoryInput> | Prisma.MenuCategoryTranslationCreateWithoutCategoryInput[] | Prisma.MenuCategoryTranslationUncheckedCreateWithoutCategoryInput[]
  connectOrCreate?: Prisma.MenuCategoryTranslationCreateOrConnectWithoutCategoryInput | Prisma.MenuCategoryTranslationCreateOrConnectWithoutCategoryInput[]
  upsert?: Prisma.MenuCategoryTranslationUpsertWithWhereUniqueWithoutCategoryInput | Prisma.MenuCategoryTranslationUpsertWithWhereUniqueWithoutCategoryInput[]
  createMany?: Prisma.MenuCategoryTranslationCreateManyCategoryInputEnvelope
  set?: Prisma.MenuCategoryTranslationWhereUniqueInput | Prisma.MenuCategoryTranslationWhereUniqueInput[]
  disconnect?: Prisma.MenuCategoryTranslationWhereUniqueInput | Prisma.MenuCategoryTranslationWhereUniqueInput[]
  delete?: Prisma.MenuCategoryTranslationWhereUniqueInput | Prisma.MenuCategoryTranslationWhereUniqueInput[]
  connect?: Prisma.MenuCategoryTranslationWhereUniqueInput | Prisma.MenuCategoryTranslationWhereUniqueInput[]
  update?: Prisma.MenuCategoryTranslationUpdateWithWhereUniqueWithoutCategoryInput | Prisma.MenuCategoryTranslationUpdateWithWhereUniqueWithoutCategoryInput[]
  updateMany?: Prisma.MenuCategoryTranslationUpdateManyWithWhereWithoutCategoryInput | Prisma.MenuCategoryTranslationUpdateManyWithWhereWithoutCategoryInput[]
  deleteMany?: Prisma.MenuCategoryTranslationScalarWhereInput | Prisma.MenuCategoryTranslationScalarWhereInput[]
}

export type EnumLanguageFieldUpdateOperationsInput = {
  set?: $Enums.Language
}

export type MenuCategoryTranslationCreateWithoutCategoryInput = {
  id?: string
  language: $Enums.Language
  title: string
  description?: string | null
}

export type MenuCategoryTranslationUncheckedCreateWithoutCategoryInput = {
  id?: string
  language: $Enums.Language
  title: string
  description?: string | null
}

export type MenuCategoryTranslationCreateOrConnectWithoutCategoryInput = {
  where: Prisma.MenuCategoryTranslationWhereUniqueInput
  create: Prisma.XOR<Prisma.MenuCategoryTranslationCreateWithoutCategoryInput, Prisma.MenuCategoryTranslationUncheckedCreateWithoutCategoryInput>
}

export type MenuCategoryTranslationCreateManyCategoryInputEnvelope = {
  data: Prisma.MenuCategoryTranslationCreateManyCategoryInput | Prisma.MenuCategoryTranslationCreateManyCategoryInput[]
  skipDuplicates?: boolean
}

export type MenuCategoryTranslationUpsertWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.MenuCategoryTranslationWhereUniqueInput
  update: Prisma.XOR<Prisma.MenuCategoryTranslationUpdateWithoutCategoryInput, Prisma.MenuCategoryTranslationUncheckedUpdateWithoutCategoryInput>
  create: Prisma.XOR<Prisma.MenuCategoryTranslationCreateWithoutCategoryInput, Prisma.MenuCategoryTranslationUncheckedCreateWithoutCategoryInput>
}

export type MenuCategoryTranslationUpdateWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.MenuCategoryTranslationWhereUniqueInput
  data: Prisma.XOR<Prisma.MenuCategoryTranslationUpdateWithoutCategoryInput, Prisma.MenuCategoryTranslationUncheckedUpdateWithoutCategoryInput>
}

export type MenuCategoryTranslationUpdateManyWithWhereWithoutCategoryInput = {
  where: Prisma.MenuCategoryTranslationScalarWhereInput
  data: Prisma.XOR<Prisma.MenuCategoryTranslationUpdateManyMutationInput, Prisma.MenuCategoryTranslationUncheckedUpdateManyWithoutCategoryInput>
}

export type MenuCategoryTranslationScalarWhereInput = {
  AND?: Prisma.MenuCategoryTranslationScalarWhereInput | Prisma.MenuCategoryTranslationScalarWhereInput[]
  OR?: Prisma.MenuCategoryTranslationScalarWhereInput[]
  NOT?: Prisma.MenuCategoryTranslationScalarWhereInput | Prisma.MenuCategoryTranslationScalarWhereInput[]
  id?: Prisma.StringFilter<"MenuCategoryTranslation"> | string
  language?: Prisma.EnumLanguageFilter<"MenuCategoryTranslation"> | $Enums.Language
  title?: Prisma.StringFilter<"MenuCategoryTranslation"> | string
  description?: Prisma.StringNullableFilter<"MenuCategoryTranslation"> | string | null
  categoryId?: Prisma.StringFilter<"MenuCategoryTranslation"> | string
}

export type MenuCategoryTranslationCreateManyCategoryInput = {
  id?: string
  language: $Enums.Language
  title: string
  description?: string | null
}

export type MenuCategoryTranslationUpdateWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.EnumLanguageFieldUpdateOperationsInput | $Enums.Language
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MenuCategoryTranslationUncheckedUpdateWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.EnumLanguageFieldUpdateOperationsInput | $Enums.Language
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MenuCategoryTranslationUncheckedUpdateManyWithoutCategoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.EnumLanguageFieldUpdateOperationsInput | $Enums.Language
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type MenuCategoryTranslationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  language?: boolean
  title?: boolean
  description?: boolean
  categoryId?: boolean
  category?: boolean | Prisma.MenuCategoryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["menuCategoryTranslation"]>

export type MenuCategoryTranslationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  language?: boolean
  title?: boolean
  description?: boolean
  categoryId?: boolean
  category?: boolean | Prisma.MenuCategoryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["menuCategoryTranslation"]>

export type MenuCategoryTranslationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  language?: boolean
  title?: boolean
  description?: boolean
  categoryId?: boolean
  category?: boolean | Prisma.MenuCategoryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["menuCategoryTranslation"]>

export type MenuCategoryTranslationSelectScalar = {
  id?: boolean
  language?: boolean
  title?: boolean
  description?: boolean
  categoryId?: boolean
}

export type MenuCategoryTranslationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "language" | "title" | "description" | "categoryId", ExtArgs["result"]["menuCategoryTranslation"]>
export type MenuCategoryTranslationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.MenuCategoryDefaultArgs<ExtArgs>
}
export type MenuCategoryTranslationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.MenuCategoryDefaultArgs<ExtArgs>
}
export type MenuCategoryTranslationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  category?: boolean | Prisma.MenuCategoryDefaultArgs<ExtArgs>
}

export type $MenuCategoryTranslationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MenuCategoryTranslation"
  objects: {
    category: Prisma.$MenuCategoryPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    language: $Enums.Language
    title: string
    description: string | null
    categoryId: string
  }, ExtArgs["result"]["menuCategoryTranslation"]>
  composites: {}
}

export type MenuCategoryTranslationGetPayload<S extends boolean | null | undefined | MenuCategoryTranslationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MenuCategoryTranslationPayload, S>

export type MenuCategoryTranslationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MenuCategoryTranslationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MenuCategoryTranslationCountAggregateInputType | true
  }

export interface MenuCategoryTranslationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MenuCategoryTranslation'], meta: { name: 'MenuCategoryTranslation' } }
  /**
   * Find zero or one MenuCategoryTranslation that matches the filter.
   * @param {MenuCategoryTranslationFindUniqueArgs} args - Arguments to find a MenuCategoryTranslation
   * @example
   * // Get one MenuCategoryTranslation
   * const menuCategoryTranslation = await prisma.menuCategoryTranslation.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MenuCategoryTranslationFindUniqueArgs>(args: Prisma.SelectSubset<T, MenuCategoryTranslationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MenuCategoryTranslationClient<runtime.Types.Result.GetResult<Prisma.$MenuCategoryTranslationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MenuCategoryTranslation that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MenuCategoryTranslationFindUniqueOrThrowArgs} args - Arguments to find a MenuCategoryTranslation
   * @example
   * // Get one MenuCategoryTranslation
   * const menuCategoryTranslation = await prisma.menuCategoryTranslation.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MenuCategoryTranslationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MenuCategoryTranslationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MenuCategoryTranslationClient<runtime.Types.Result.GetResult<Prisma.$MenuCategoryTranslationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MenuCategoryTranslation that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MenuCategoryTranslationFindFirstArgs} args - Arguments to find a MenuCategoryTranslation
   * @example
   * // Get one MenuCategoryTranslation
   * const menuCategoryTranslation = await prisma.menuCategoryTranslation.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MenuCategoryTranslationFindFirstArgs>(args?: Prisma.SelectSubset<T, MenuCategoryTranslationFindFirstArgs<ExtArgs>>): Prisma.Prisma__MenuCategoryTranslationClient<runtime.Types.Result.GetResult<Prisma.$MenuCategoryTranslationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MenuCategoryTranslation that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MenuCategoryTranslationFindFirstOrThrowArgs} args - Arguments to find a MenuCategoryTranslation
   * @example
   * // Get one MenuCategoryTranslation
   * const menuCategoryTranslation = await prisma.menuCategoryTranslation.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MenuCategoryTranslationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MenuCategoryTranslationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MenuCategoryTranslationClient<runtime.Types.Result.GetResult<Prisma.$MenuCategoryTranslationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MenuCategoryTranslations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MenuCategoryTranslationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MenuCategoryTranslations
   * const menuCategoryTranslations = await prisma.menuCategoryTranslation.findMany()
   * 
   * // Get first 10 MenuCategoryTranslations
   * const menuCategoryTranslations = await prisma.menuCategoryTranslation.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const menuCategoryTranslationWithIdOnly = await prisma.menuCategoryTranslation.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MenuCategoryTranslationFindManyArgs>(args?: Prisma.SelectSubset<T, MenuCategoryTranslationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MenuCategoryTranslationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MenuCategoryTranslation.
   * @param {MenuCategoryTranslationCreateArgs} args - Arguments to create a MenuCategoryTranslation.
   * @example
   * // Create one MenuCategoryTranslation
   * const MenuCategoryTranslation = await prisma.menuCategoryTranslation.create({
   *   data: {
   *     // ... data to create a MenuCategoryTranslation
   *   }
   * })
   * 
   */
  create<T extends MenuCategoryTranslationCreateArgs>(args: Prisma.SelectSubset<T, MenuCategoryTranslationCreateArgs<ExtArgs>>): Prisma.Prisma__MenuCategoryTranslationClient<runtime.Types.Result.GetResult<Prisma.$MenuCategoryTranslationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MenuCategoryTranslations.
   * @param {MenuCategoryTranslationCreateManyArgs} args - Arguments to create many MenuCategoryTranslations.
   * @example
   * // Create many MenuCategoryTranslations
   * const menuCategoryTranslation = await prisma.menuCategoryTranslation.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MenuCategoryTranslationCreateManyArgs>(args?: Prisma.SelectSubset<T, MenuCategoryTranslationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MenuCategoryTranslations and returns the data saved in the database.
   * @param {MenuCategoryTranslationCreateManyAndReturnArgs} args - Arguments to create many MenuCategoryTranslations.
   * @example
   * // Create many MenuCategoryTranslations
   * const menuCategoryTranslation = await prisma.menuCategoryTranslation.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MenuCategoryTranslations and only return the `id`
   * const menuCategoryTranslationWithIdOnly = await prisma.menuCategoryTranslation.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MenuCategoryTranslationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MenuCategoryTranslationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MenuCategoryTranslationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MenuCategoryTranslation.
   * @param {MenuCategoryTranslationDeleteArgs} args - Arguments to delete one MenuCategoryTranslation.
   * @example
   * // Delete one MenuCategoryTranslation
   * const MenuCategoryTranslation = await prisma.menuCategoryTranslation.delete({
   *   where: {
   *     // ... filter to delete one MenuCategoryTranslation
   *   }
   * })
   * 
   */
  delete<T extends MenuCategoryTranslationDeleteArgs>(args: Prisma.SelectSubset<T, MenuCategoryTranslationDeleteArgs<ExtArgs>>): Prisma.Prisma__MenuCategoryTranslationClient<runtime.Types.Result.GetResult<Prisma.$MenuCategoryTranslationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MenuCategoryTranslation.
   * @param {MenuCategoryTranslationUpdateArgs} args - Arguments to update one MenuCategoryTranslation.
   * @example
   * // Update one MenuCategoryTranslation
   * const menuCategoryTranslation = await prisma.menuCategoryTranslation.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MenuCategoryTranslationUpdateArgs>(args: Prisma.SelectSubset<T, MenuCategoryTranslationUpdateArgs<ExtArgs>>): Prisma.Prisma__MenuCategoryTranslationClient<runtime.Types.Result.GetResult<Prisma.$MenuCategoryTranslationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MenuCategoryTranslations.
   * @param {MenuCategoryTranslationDeleteManyArgs} args - Arguments to filter MenuCategoryTranslations to delete.
   * @example
   * // Delete a few MenuCategoryTranslations
   * const { count } = await prisma.menuCategoryTranslation.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MenuCategoryTranslationDeleteManyArgs>(args?: Prisma.SelectSubset<T, MenuCategoryTranslationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MenuCategoryTranslations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MenuCategoryTranslationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MenuCategoryTranslations
   * const menuCategoryTranslation = await prisma.menuCategoryTranslation.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MenuCategoryTranslationUpdateManyArgs>(args: Prisma.SelectSubset<T, MenuCategoryTranslationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MenuCategoryTranslations and returns the data updated in the database.
   * @param {MenuCategoryTranslationUpdateManyAndReturnArgs} args - Arguments to update many MenuCategoryTranslations.
   * @example
   * // Update many MenuCategoryTranslations
   * const menuCategoryTranslation = await prisma.menuCategoryTranslation.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MenuCategoryTranslations and only return the `id`
   * const menuCategoryTranslationWithIdOnly = await prisma.menuCategoryTranslation.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MenuCategoryTranslationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MenuCategoryTranslationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MenuCategoryTranslationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MenuCategoryTranslation.
   * @param {MenuCategoryTranslationUpsertArgs} args - Arguments to update or create a MenuCategoryTranslation.
   * @example
   * // Update or create a MenuCategoryTranslation
   * const menuCategoryTranslation = await prisma.menuCategoryTranslation.upsert({
   *   create: {
   *     // ... data to create a MenuCategoryTranslation
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MenuCategoryTranslation we want to update
   *   }
   * })
   */
  upsert<T extends MenuCategoryTranslationUpsertArgs>(args: Prisma.SelectSubset<T, MenuCategoryTranslationUpsertArgs<ExtArgs>>): Prisma.Prisma__MenuCategoryTranslationClient<runtime.Types.Result.GetResult<Prisma.$MenuCategoryTranslationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MenuCategoryTranslations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MenuCategoryTranslationCountArgs} args - Arguments to filter MenuCategoryTranslations to count.
   * @example
   * // Count the number of MenuCategoryTranslations
   * const count = await prisma.menuCategoryTranslation.count({
   *   where: {
   *     // ... the filter for the MenuCategoryTranslations we want to count
   *   }
   * })
  **/
  count<T extends MenuCategoryTranslationCountArgs>(
    args?: Prisma.Subset<T, MenuCategoryTranslationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MenuCategoryTranslationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MenuCategoryTranslation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MenuCategoryTranslationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MenuCategoryTranslationAggregateArgs>(args: Prisma.Subset<T, MenuCategoryTranslationAggregateArgs>): Prisma.PrismaPromise<GetMenuCategoryTranslationAggregateType<T>>

  /**
   * Group by MenuCategoryTranslation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MenuCategoryTranslationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MenuCategoryTranslationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MenuCategoryTranslationGroupByArgs['orderBy'] }
      : { orderBy?: MenuCategoryTranslationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MenuCategoryTranslationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMenuCategoryTranslationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MenuCategoryTranslation model
 */
readonly fields: MenuCategoryTranslationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MenuCategoryTranslation.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MenuCategoryTranslationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  category<T extends Prisma.MenuCategoryDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MenuCategoryDefaultArgs<ExtArgs>>): Prisma.Prisma__MenuCategoryClient<runtime.Types.Result.GetResult<Prisma.$MenuCategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MenuCategoryTranslation model
 */
export interface MenuCategoryTranslationFieldRefs {
  readonly id: Prisma.FieldRef<"MenuCategoryTranslation", 'String'>
  readonly language: Prisma.FieldRef<"MenuCategoryTranslation", 'Language'>
  readonly title: Prisma.FieldRef<"MenuCategoryTranslation", 'String'>
  readonly description: Prisma.FieldRef<"MenuCategoryTranslation", 'String'>
  readonly categoryId: Prisma.FieldRef<"MenuCategoryTranslation", 'String'>
}
    

// Custom InputTypes
/**
 * MenuCategoryTranslation findUnique
 */
export type MenuCategoryTranslationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuCategoryTranslation
   */
  select?: Prisma.MenuCategoryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuCategoryTranslation
   */
  omit?: Prisma.MenuCategoryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuCategoryTranslationInclude<ExtArgs> | null
  /**
   * Filter, which MenuCategoryTranslation to fetch.
   */
  where: Prisma.MenuCategoryTranslationWhereUniqueInput
}

/**
 * MenuCategoryTranslation findUniqueOrThrow
 */
export type MenuCategoryTranslationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuCategoryTranslation
   */
  select?: Prisma.MenuCategoryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuCategoryTranslation
   */
  omit?: Prisma.MenuCategoryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuCategoryTranslationInclude<ExtArgs> | null
  /**
   * Filter, which MenuCategoryTranslation to fetch.
   */
  where: Prisma.MenuCategoryTranslationWhereUniqueInput
}

/**
 * MenuCategoryTranslation findFirst
 */
export type MenuCategoryTranslationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuCategoryTranslation
   */
  select?: Prisma.MenuCategoryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuCategoryTranslation
   */
  omit?: Prisma.MenuCategoryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuCategoryTranslationInclude<ExtArgs> | null
  /**
   * Filter, which MenuCategoryTranslation to fetch.
   */
  where?: Prisma.MenuCategoryTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MenuCategoryTranslations to fetch.
   */
  orderBy?: Prisma.MenuCategoryTranslationOrderByWithRelationInput | Prisma.MenuCategoryTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MenuCategoryTranslations.
   */
  cursor?: Prisma.MenuCategoryTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MenuCategoryTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MenuCategoryTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MenuCategoryTranslations.
   */
  distinct?: Prisma.MenuCategoryTranslationScalarFieldEnum | Prisma.MenuCategoryTranslationScalarFieldEnum[]
}

/**
 * MenuCategoryTranslation findFirstOrThrow
 */
export type MenuCategoryTranslationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuCategoryTranslation
   */
  select?: Prisma.MenuCategoryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuCategoryTranslation
   */
  omit?: Prisma.MenuCategoryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuCategoryTranslationInclude<ExtArgs> | null
  /**
   * Filter, which MenuCategoryTranslation to fetch.
   */
  where?: Prisma.MenuCategoryTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MenuCategoryTranslations to fetch.
   */
  orderBy?: Prisma.MenuCategoryTranslationOrderByWithRelationInput | Prisma.MenuCategoryTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MenuCategoryTranslations.
   */
  cursor?: Prisma.MenuCategoryTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MenuCategoryTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MenuCategoryTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MenuCategoryTranslations.
   */
  distinct?: Prisma.MenuCategoryTranslationScalarFieldEnum | Prisma.MenuCategoryTranslationScalarFieldEnum[]
}

/**
 * MenuCategoryTranslation findMany
 */
export type MenuCategoryTranslationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuCategoryTranslation
   */
  select?: Prisma.MenuCategoryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuCategoryTranslation
   */
  omit?: Prisma.MenuCategoryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuCategoryTranslationInclude<ExtArgs> | null
  /**
   * Filter, which MenuCategoryTranslations to fetch.
   */
  where?: Prisma.MenuCategoryTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MenuCategoryTranslations to fetch.
   */
  orderBy?: Prisma.MenuCategoryTranslationOrderByWithRelationInput | Prisma.MenuCategoryTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MenuCategoryTranslations.
   */
  cursor?: Prisma.MenuCategoryTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MenuCategoryTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MenuCategoryTranslations.
   */
  skip?: number
  distinct?: Prisma.MenuCategoryTranslationScalarFieldEnum | Prisma.MenuCategoryTranslationScalarFieldEnum[]
}

/**
 * MenuCategoryTranslation create
 */
export type MenuCategoryTranslationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuCategoryTranslation
   */
  select?: Prisma.MenuCategoryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuCategoryTranslation
   */
  omit?: Prisma.MenuCategoryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuCategoryTranslationInclude<ExtArgs> | null
  /**
   * The data needed to create a MenuCategoryTranslation.
   */
  data: Prisma.XOR<Prisma.MenuCategoryTranslationCreateInput, Prisma.MenuCategoryTranslationUncheckedCreateInput>
}

/**
 * MenuCategoryTranslation createMany
 */
export type MenuCategoryTranslationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MenuCategoryTranslations.
   */
  data: Prisma.MenuCategoryTranslationCreateManyInput | Prisma.MenuCategoryTranslationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MenuCategoryTranslation createManyAndReturn
 */
export type MenuCategoryTranslationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuCategoryTranslation
   */
  select?: Prisma.MenuCategoryTranslationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MenuCategoryTranslation
   */
  omit?: Prisma.MenuCategoryTranslationOmit<ExtArgs> | null
  /**
   * The data used to create many MenuCategoryTranslations.
   */
  data: Prisma.MenuCategoryTranslationCreateManyInput | Prisma.MenuCategoryTranslationCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuCategoryTranslationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * MenuCategoryTranslation update
 */
export type MenuCategoryTranslationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuCategoryTranslation
   */
  select?: Prisma.MenuCategoryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuCategoryTranslation
   */
  omit?: Prisma.MenuCategoryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuCategoryTranslationInclude<ExtArgs> | null
  /**
   * The data needed to update a MenuCategoryTranslation.
   */
  data: Prisma.XOR<Prisma.MenuCategoryTranslationUpdateInput, Prisma.MenuCategoryTranslationUncheckedUpdateInput>
  /**
   * Choose, which MenuCategoryTranslation to update.
   */
  where: Prisma.MenuCategoryTranslationWhereUniqueInput
}

/**
 * MenuCategoryTranslation updateMany
 */
export type MenuCategoryTranslationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MenuCategoryTranslations.
   */
  data: Prisma.XOR<Prisma.MenuCategoryTranslationUpdateManyMutationInput, Prisma.MenuCategoryTranslationUncheckedUpdateManyInput>
  /**
   * Filter which MenuCategoryTranslations to update
   */
  where?: Prisma.MenuCategoryTranslationWhereInput
  /**
   * Limit how many MenuCategoryTranslations to update.
   */
  limit?: number
}

/**
 * MenuCategoryTranslation updateManyAndReturn
 */
export type MenuCategoryTranslationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuCategoryTranslation
   */
  select?: Prisma.MenuCategoryTranslationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MenuCategoryTranslation
   */
  omit?: Prisma.MenuCategoryTranslationOmit<ExtArgs> | null
  /**
   * The data used to update MenuCategoryTranslations.
   */
  data: Prisma.XOR<Prisma.MenuCategoryTranslationUpdateManyMutationInput, Prisma.MenuCategoryTranslationUncheckedUpdateManyInput>
  /**
   * Filter which MenuCategoryTranslations to update
   */
  where?: Prisma.MenuCategoryTranslationWhereInput
  /**
   * Limit how many MenuCategoryTranslations to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuCategoryTranslationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * MenuCategoryTranslation upsert
 */
export type MenuCategoryTranslationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuCategoryTranslation
   */
  select?: Prisma.MenuCategoryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuCategoryTranslation
   */
  omit?: Prisma.MenuCategoryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuCategoryTranslationInclude<ExtArgs> | null
  /**
   * The filter to search for the MenuCategoryTranslation to update in case it exists.
   */
  where: Prisma.MenuCategoryTranslationWhereUniqueInput
  /**
   * In case the MenuCategoryTranslation found by the `where` argument doesn't exist, create a new MenuCategoryTranslation with this data.
   */
  create: Prisma.XOR<Prisma.MenuCategoryTranslationCreateInput, Prisma.MenuCategoryTranslationUncheckedCreateInput>
  /**
   * In case the MenuCategoryTranslation was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MenuCategoryTranslationUpdateInput, Prisma.MenuCategoryTranslationUncheckedUpdateInput>
}

/**
 * MenuCategoryTranslation delete
 */
export type MenuCategoryTranslationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuCategoryTranslation
   */
  select?: Prisma.MenuCategoryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuCategoryTranslation
   */
  omit?: Prisma.MenuCategoryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuCategoryTranslationInclude<ExtArgs> | null
  /**
   * Filter which MenuCategoryTranslation to delete.
   */
  where: Prisma.MenuCategoryTranslationWhereUniqueInput
}

/**
 * MenuCategoryTranslation deleteMany
 */
export type MenuCategoryTranslationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MenuCategoryTranslations to delete
   */
  where?: Prisma.MenuCategoryTranslationWhereInput
  /**
   * Limit how many MenuCategoryTranslations to delete.
   */
  limit?: number
}

/**
 * MenuCategoryTranslation without action
 */
export type MenuCategoryTranslationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuCategoryTranslation
   */
  select?: Prisma.MenuCategoryTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuCategoryTranslation
   */
  omit?: Prisma.MenuCategoryTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuCategoryTranslationInclude<ExtArgs> | null
}
